# Generated by Django 5.1.1 on 2024-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duduapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bubu_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='dudu_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='watched_status',
            field=models.BooleanField(default=False),
        ),
    ]
