# Generated by Django 5.1.1 on 2024-10-14 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duduapp', '0002_movie_bubu_rating_movie_dudu_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='bubu_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='dudu_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
