# Generated by Django 5.1.1 on 2024-10-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duduapp', '0004_movie_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('dudu_rating', models.IntegerField(default=0)),
                ('bubu_rating', models.IntegerField(default=0)),
                ('dudu_notes', models.TextField(blank=True, null=True)),
                ('bubu_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
