# Generated by Django 5.1.1 on 2024-10-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duduapp', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('not yet', 'Not yet'), ('we did', 'We did')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
