# Generated by Django 5.1.1 on 2024-10-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duduapp', '0008_dateimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description_dudu', models.TextField()),
                ('description_bubu', models.TextField()),
                ('mood_dudu', models.CharField(max_length=50)),
                ('mood_bubu', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='diary_photos/')),
            ],
        ),
    ]
