# Generated by Django 5.1.1 on 2024-11-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duduapp', '0009_diaryeintrag'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbarrassingMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('embarrassment_level', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
            ],
        ),
    ]
