# Generated by Django 5.1.1 on 2024-11-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duduapp', '0011_dream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='List of ingredients')),
                ('steps', models.TextField(help_text='Steps for cooking/baking')),
                ('tried', models.BooleanField(default=False)),
                ('rating_dudu', models.PositiveIntegerField(blank=True, null=True)),
                ('rating_bubu', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
