# Generated by Django 5.1.1 on 2024-11-10 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duduapp', '0012_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('special_notes', models.TextField()),
                ('time_together', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='duduapp.timetogether')),
            ],
        ),
    ]
