# Generated by Django 5.1.1 on 2024-11-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duduapp', '0013_timetogether_timeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetogether',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timetogether',
            name='start_time',
            field=models.DateField(),
        ),
    ]
