# Generated by Django 5.1.1 on 2024-11-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duduapp', '0014_alter_timetogether_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german_word', models.CharField(max_length=100, verbose_name='german word')),
                ('portuguese_word', models.CharField(max_length=100, verbose_name='portuguese word')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='category')),
                ('difficulty', models.IntegerField(choices=[(1, 'easy'), (2, 'medium'), (3, 'hard')], default=1, verbose_name='difficulty')),
            ],
        ),
    ]
